TRUNCATE TABLE accounts;
/* 21/08/2020 */
INSERT INTO `accounts` (`id`, `email`, `password`, `balance`, `last_cashout`, `type`, `created_at`, `updated_at`, `deleted_at`, `btc_addr`, `refferer`,`last_ip`, `message`) VALUES ('1', '17j4ck@gmail.com', 'test1234&', NULL, NULL, 1, NOW(), NOW(), NULL, '1GKsdXFuWuKv88qR2bsVnaYb6shTeV45Ya', 0, '', '');
INSERT INTO `accounts` (`id`, `email`, `password`, `balance`, `last_cashout`, `type`, `created_at`, `updated_at`, `deleted_at`, `btc_addr`, `refferer`,`last_ip`, `message`) VALUES ('2', '17j4ck.1@gmail.com', 'test1234&', NULL, NULL, 0, NOW(), NOW(), NULL, '', 38665041, '', '');
INSERT INTO `accounts` (`id`, `email`, `password`, `balance`, `last_cashout`, `type`, `created_at`, `updated_at`, `deleted_at`, `btc_addr`, `refferer`,`last_ip`, `message`) VALUES ('3', '17j4ck.2@gmail.com', 'test1234&', NULL, NULL, 0, NOW(), NOW(), NULL, '', 38665041, '', '');
INSERT INTO `accounts` (`id`, `email`, `password`, `balance`, `last_cashout`, `type`, `created_at`, `updated_at`, `deleted_at`, `btc_addr`, `refferer`,`last_ip`, `message`) VALUES ('4', '17j4ck.3@gmail.com', 'test1234&', NULL, NULL, 0, NOW(), NOW(), NULL, '', 38665041, '', '');
INSERT INTO `accounts` (`id`, `email`, `password`, `balance`, `last_cashout`, `type`, `created_at`, `updated_at`, `deleted_at`, `btc_addr`, `refferer`,`last_ip`, `message`) VALUES ('5', '17j4ck.4@gmail.com', 'test1234&', NULL, NULL, 0, NOW(), NOW(), NULL, '', 38665041, '', '');
INSERT INTO `accounts` (`id`, `email`, `password`, `balance`, `last_cashout`, `type`, `created_at`, `updated_at`, `deleted_at`, `btc_addr`, `refferer`,`last_ip`, `message`) VALUES ('6', '17j4ck.5@laposte.net', 'Test1234', NULL, NULL, 0, NOW(), NOW(), NULL, '', 38665041, '', '');
INSERT INTO `accounts` (`id`, `email`, `password`, `balance`, `last_cashout`, `type`, `created_at`, `updated_at`, `deleted_at`, `btc_addr`, `refferer`,`last_ip`, `message`) VALUES ('7', '17j4ck.6@laposte.net', 'Test1234', NULL, NULL, 0, NOW(), NOW(), NULL, '', 38665041, '', '');
/* 22/08/2020 */
INSERT INTO `accounts` (`id`, `email`, `password`, `balance`, `last_cashout`, `type`, `created_at`, `updated_at`, `deleted_at`, `btc_addr`, `refferer`,`last_ip`, `message`) VALUES ('8', '17j4ck.7@laposte.net', 'Test1234', NULL, NULL, 0, NOW(), NOW(), NULL, '', 38665041, '', '');
INSERT INTO `accounts` (`id`, `email`, `password`, `balance`, `last_cashout`, `type`, `created_at`, `updated_at`, `deleted_at`, `btc_addr`, `refferer`,`last_ip`, `message`) VALUES ('9', '17j4ck.8@laposte.net', 'Test1234', NULL, NULL, 0, NOW(), NOW(), NULL, '', 38665041, '', '');
INSERT INTO `accounts` (`id`, `email`, `password`, `balance`, `last_cashout`, `type`, `created_at`, `updated_at`, `deleted_at`, `btc_addr`, `refferer`,`last_ip`, `message`) VALUES ('10', '17j4ck.9@laposte.net', 'Test1234', NULL, NULL, 0, NOW(), NOW(), NULL, '', 38665041, '', '');
INSERT INTO `accounts` (`id`, `email`, `password`, `balance`, `last_cashout`, `type`, `created_at`, `updated_at`, `deleted_at`, `btc_addr`, `refferer`,`last_ip`, `message`) VALUES ('11', '17j4ck.10@laposte.net', 'Test1234', NULL, NULL, 0, NOW(), NOW(), NULL, '', 38665041, '', '');
INSERT INTO `accounts` (`id`, `email`, `password`, `balance`, `last_cashout`, `type`, `created_at`, `updated_at`, `deleted_at`, `btc_addr`, `refferer`,`last_ip`, `message`) VALUES ('12', '17j4ck.11@laposte.net', 'Test1234', NULL, NULL, 0, NOW(), NOW(), NULL, '', 38665041, '', '');
INSERT INTO `accounts` (`id`, `email`, `password`, `balance`, `last_cashout`, `type`, `created_at`, `updated_at`, `deleted_at`, `btc_addr`, `refferer`,`last_ip`, `message`) VALUES ('13', '17j4ck.12@laposte.net', 'Test1234', NULL, NULL, 0, NOW(), NOW(), NULL, '', 38665041, '', '');
INSERT INTO `accounts` (`id`, `email`, `password`, `balance`, `last_cashout`, `type`, `created_at`, `updated_at`, `deleted_at`, `btc_addr`, `refferer`,`last_ip`, `message`) VALUES ('14', '17j4ck.13@laposte.net', 'Test1234', NULL, NULL, 0, NOW(), NOW(), NULL, '', 38665041, '', '');
INSERT INTO `accounts` (`id`, `email`, `password`, `balance`, `last_cashout`, `type`, `created_at`, `updated_at`, `deleted_at`, `btc_addr`, `refferer`,`last_ip`, `message`) VALUES ('15', '17j4ck.14@laposte.net', 'Test1234', NULL, NULL, 0, NOW(), NOW(), NULL, '', 38665041, '', '');
INSERT INTO `accounts` (`id`, `email`, `password`, `balance`, `last_cashout`, `type`, `created_at`, `updated_at`, `deleted_at`, `btc_addr`, `refferer`,`last_ip`, `message`) VALUES ('16', '17j4ck.16@laposte.net', 'Test1234', NULL, NULL, 0, NOW(), NOW(), NULL, '', 38665041, '', '');
INSERT INTO `accounts` (`id`, `email`, `password`, `balance`, `last_cashout`, `type`, `created_at`, `updated_at`, `deleted_at`, `btc_addr`, `refferer`,`last_ip`, `message`) VALUES ('17', '17j4ck.17@gmx.com', 'Yoshi213&', NULL, NULL, 0, NOW(), NOW(), NULL, '', 38665041, '', '');
